### ISSUE TITLE
dns add-on does not exist anymore in repo

### ISSUE THREAD

**Issue by jalbstmeijer** [skippbox/configk8s#2]
script deploy-dns.sh tries to fetch these urls

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/skydns-rc.yaml.in
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/skydns-svc.yaml.in

But https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns does not exist anymore

**Comment by sebgoa** [comment]
@jalbstmeijer yes good catch, looks like it got moved to
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-dns/skydns-rc.yaml.sed

**Comment by sebgoa** [comment]
you can also find them in the `json/` directory in this repo.

I will update the makefile...feel free to send a PR :)

**Comment by jalbstmeijer** [comment]
> looks like it got moved to
> https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-dns/skydns-rc.yaml.sed

I assume you mean:  

https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/saltbase/salt/kube-dns/skydns-rc.yaml.in
and
https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/saltbase/salt/kube-dns/skydns-svc.yaml.in

The sed actions on skydns-rc.yaml.in leave:

```
{{ pillar['federations_domain_map'] }}
```

causing

```
yaml: line 78: could not find expected ':'
```

**Comment by sebgoa** [comment]
Should be fixed now.

Note that the latest kmachine has a `deploy` command that takes care of all of this.

`kmachine deploy dns foobar`

**Comment by jalbstmeijer** [comment]
was the reported "{{ pillar['federations_domain_map'] }}" issue solved? I just removed that line for now.

**Comment by jalbstmeijer** [comment]
"kmachine deploy dns foobar"

So deploy-addons.sh is obsolete for kmachine users?

**Comment by sebgoa** [comment]
configk8s is just a set of convenience scripts that show how to deploy the add ons.

but in kmachine we embedded the yaml files and automated the deployment, so indeed you can do:

```
kmachine deploy dns <machinename>
kmachine deploy dashboard <machinename>
```

And you will get things running.

Sorry if this was not clear. I will check the readme of kmachine.
